image:
  repository: quay.io/acoustid/postgresql
  tag: v2019.10.15-pg11
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  # name:

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 1Gi

metrics:
  enabled: false
  port: 8080
  annotations: {}

exporter:
  enabled: true
  port: 9187

sentinel:
  replicas: 2
  resources: {}

proxy:
  replicas: 2
  resources: {}

keeper:
  replicas: 2
  resources: {}

superuser:
  # secretName:
  username: postgres
  password:

replication:
  # secretName:
  username: replication
  password:

initClusterSpec:
  initMode: new
  usePgrewind: true
  automaticPgRestart: true
  dbWaitReadyTimeout: 120s

slony:
  enabled: false
  clusterName: ""
  databaseName: ""

backup:
  enabled: false
  bucket:
  prefix:
  aws_access_key_id:
  aws_secret_access_key:

debug: false

# nameOverride:
# fullnameOverride:

labels: []

annotations: []
