{{- if .Values.import.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acoustid-server.fullname" . }}-import
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: import
spec:
  {{- if .Values.api.replicaCount }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "acoustid-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: import
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acoustid-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: import
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-import
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/acoustid/server/admin/docker/run-import.sh
          env:
            - name: ACOUSTID_CONFIG
              value: /etc/acoustid/acoustid.conf
            - name: ACOUSTID_INDEX_PORT
              value: "6080"
          volumeMounts:
            - mountPath: /etc/secrets/redis
              name: redis-password
            - mountPath: /etc/secrets/postgresql/acoustid
              name: postgresql-user-acoustid
            - mountPath: /etc/acoustid
              name: acoustid-config
            - mountPath: /etc/secrets/acoustid
              name: acoustid-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: postgresql-user-acoustid
          secret:
            defaultMode: 420
            secretName: postgresql-user-acoustid
        - name: redis-password
          secret:
            defaultMode: 420
            secretName: redis-password
        - configMap:
            defaultMode: 420
            name: acoustid-server-config
          name: acoustid-config
        - name: acoustid-secrets
          secret:
            defaultMode: 420
            secretName: acoustid-server-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
