{{- if .Values.cron.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acoustid-server.fullname" . }}-cron
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "acoustid-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cron
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acoustid-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cron
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-cron
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/acoustid/server/admin/docker/run-cron.sh
          env:
            - name: ACOUSTID_CONFIG
              value: /etc/acoustid/acoustid.conf
            - name: ACOUSTID_INDEX_PORT
              value: "6080"
          volumeMounts:
            - mountPath: /etc/acoustid
              name: acoustid-config
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      volumes:
        - name: acoustid-config
          configMap:
            defaultMode: 420
            name: {{ include "acoustid-server.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
