{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acoustid-server.fullname" . }}-web
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acoustid-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
