{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "redis.fullname" . }}-pdb
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis.matchLabels" . | nindent 4 }}
      app.kubernetes.io/component: redis
  {{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}
