{{- if and .Values.auth (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.authKey }}: {{ .Values.redisPassword | b64enc | quote }}
{{- end -}}
