{{- $fullName := include "redis.fullname" . }}
{{- $replicas := int .Values.replicas }}
{{- $root := . }}
{{- range $i := until $replicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-announce-{{ $i }}
  labels:
    {{- include "redis.labels" $root | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {{- if $root.Values.serviceAnnotations }}
{{ toYaml $root.Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: {{ $root.Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ $root.Values.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
  {{- if $root.Values.exporter.enabled }}
  - name: exporter
    port: {{ $root.Values.exporter.port }}
    protocol: TCP
    targetPort: exporter-port
  {{- end }}
  selector:
    {{- include "redis.matchLabels" $root | nindent 4 }}
    app.kubernetes.io/component: redis
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-{{ $i }}
{{- end }}
