{{- if and .Values.serviceAccount.create  .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
{{- end }}
