apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
{{- if .Values.exporter.enabled }}
  - name: exporter-port
    port: {{ .Values.exporter.port }}
    protocol: TCP
    targetPort: exporter-port
{{- end }}
  selector:
    {{- include "redis.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
