{{- if and .Values.haproxy.serviceAccount.create .Values.haproxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis.serviceAccountName" . }}-haproxy
  labels:
    {{- include "redis.labels" . | nindent 4 }}
{{- end }}
