{{- if and .Values.serviceAccount.create .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "redis.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "redis.fullname" . }}
{{- end }}
