apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acoustid-server.fullname" . }}-api
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "acoustid-server.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "acoustid-server.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-api"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: api
              containerPort: 3031
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /_health_docker
              port: 3031
            initialDelaySeconds: 3
            periodSeconds: 1
          env:
            {{- include "acoustid-server.sharedEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "acoustid-server.sharedVolumeMounts" . | nindent 12 }}
          {{- if .Values.api.resources }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "acoustid-server.sharedVolumes" . | nindent 8 }}
