apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acoustid-server.fullname" . }}-cron
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "acoustid-server.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: cron
  template:
    metadata:
      labels:
        {{- include "acoustid-server.labels" . | nindent 8 }}
        app.kubernetes.io/component: cron
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: cron
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-cron"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            {{- include "acoustid-server.sharedEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "acoustid-server.sharedVolumeMounts" . | nindent 12 }}
          {{- if .Values.cron.resources }}
          resources:
            {{- toYaml .Values.cron.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "acoustid-server.sharedVolumes" . | nindent 8 }}
