apiVersion: v1
kind: Service
metadata:
  name: {{ include "acoustid-server.fullname" . }}-static
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "acoustid-server.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: static
