{{ if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acoustid-server.fullname" . }}-web
  labels:
    {{- include "acoustid-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3032
      targetPort: 3032
      protocol: TCP
      name: http
  selector:
    {{- include "acoustid-server.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{ end }}
