apiVersion: v1
kind: Service
metadata:
  name: {{ include "acoustid-index.fullname" . }}
  labels:
    {{- include "acoustid-index.labels" . | nindent 4 }}
  annotations:
    {{- include "acoustid-index.annotations" . | nindent 8 }}
spec:
  type: ClusterIP
  ports:
    - port: 6080
      targetPort: 6080
      protocol: TCP
      name: acoustid-index
  selector:
    {{- include "acoustid-index.matchLabels" . | nindent 4 }}
