apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "acoustid-index.fullname" . }}
  labels:
    {{- include "acoustid-index.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "acoustid-index.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        {{- include "acoustid-index.labels" . | nindent 8 }}
    spec:
      containers:
        - name: index
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: acoustid-index
              containerPort: 6080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6080
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/acoustid-index
        {{ if .Values.updater.enabled }}
        - name: updater
          image: "{{ .Values.updater.image.repository }}:{{ .Values.updater.image.tag }}"
          imagePullPolicy: {{ .Values.updater.image.pullPolicy | quote }}
          env:
            - name: ACOUSTID_DATABASE_NAME
              value: {{ .Values.updater.database.name | quote }}
            - name: ACOUSTID_DATABASE_HOST
              value: {{ .Values.updater.database.host | quote }}
            - name: ACOUSTID_DATABASE_PORT
              value: {{ .Values.updater.database.port | quote }}
            - name: ACOUSTID_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.updater.database.userSecret | quote }}
                  key: username
            - name: ACOUSTID_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.updater.database.userSecret | quote }}
                  key: password
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "acoustid-index.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
