apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "acoustid-index.fullname" . }}
  labels:
    {{- include "acoustid-index.labels" . | nindent 4 }}
spec:
  serviceName: acoustid-index
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "acoustid-index.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "acoustid-index.labels" . | nindent 8 }}
      annotations:
        {{- include "acoustid-index.annotations" . | nindent 8 }}
        {{- include "acoustid-index.metricsAnnotations" . | nindent 8 }}
    spec:
      initContainers:
        - name: chown-data-dir
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/acoustid-index"]
          volumeMounts:
            - name: data
              mountPath: /var/lib/acoustid-index
      containers:
        - name: index
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "catchsegv"
            - "fpi-server"
            - "--directory"
            - "/var/lib/acoustid-index"
            - "--mmap"
            - "--address"
            - "0.0.0.0"
            - "--port"
            - "6080"
            {{- if .Values.metrics.enabled }}
            - "--metrics"
            - "--metrics-address"
            - "0.0.0.0"
            - "--metrics-port"
            - "6081"
            {{- end }}
          ports:
            - name: acoustid-index
              containerPort: 6080
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 6080
            initialDelaySeconds: 5
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/acoustid-index
        {{ if .Values.updater.enabled }}
        - name: updater
          image: "{{ .Values.updater.image.repository }}:{{ .Values.updater.image.tag }}"
          imagePullPolicy: {{ .Values.updater.image.pullPolicy | quote }}
          env:
            - name: ACOUSTID_INDEX_HOST
              value: "127.0.0.1"
            - name: ACOUSTID_INDEX_PORT
              value: "6080"
            - name: ACOUSTID_DATABASE_NAME
              value: {{ .Values.updater.database.name | quote }}
            - name: ACOUSTID_DATABASE_HOST
              value: {{ .Values.updater.database.host | quote }}
            - name: ACOUSTID_DATABASE_PORT
              value: {{ .Values.updater.database.port | quote }}
            - name: ACOUSTID_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.updater.database.userSecret | quote }}
                  key: username
            - name: ACOUSTID_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.updater.database.userSecret | quote }}
                  key: password
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "acoustid-index.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
