image:
  repository: quay.io/acoustid/acoustid-server
  tag: master
  pullPolicy: Always

api:
  enabled: true
  replicas: 6
  resources: {}

web:
  enabled: true
  replicas: 3
  resources: {}

cron:
  enabled: true
  resources: {}

import:
  enabled: true
  resources: {}

static:
  enabled: true
  replicas: 3
  resources: {}

ingress:

  web:
    enabled: false
    name: acoustid-web
    hosts:
      - acoustid.org
      - www.acoustid.org
    canary:
      enabled: false
      weight: 0
    createPrometheusRule: false

  api:
    enabled: false
    name: acoustid-api
    hosts:
      - api.acoustid.org
    canary:
      enabled: false
      weight: 0
    createPrometheusRule: false

  data:
    enabled: false
    name: acoustid-data
    hosts:
      - data.acoustid.org

database:
  userSecretName: acoustid-postgresql-user 
  app:
    name: acoustid
    readWrite:
      host: postgresql-app
      port: 5432
    readOnly:
      host: postgresql-app-all
      port: 5432
  fingerprint:
    name: acoustid
    readWrite:
      host: postgresql-fingerprint
      port: 5432
    readOnly:
      host: postgresql-fingerprint-all
      port: 5432
  ingest:
    name: acoustid
    readWrite:
      host: postgresql-ingest
      port: 5432
    readOnly:
      host: postgresql-ingest-all
      port: 5432
  musicbrainz:
    name: musicbrainz
    readWrite:
      host: postgresql-musicbrainz
      port: 5432
    readOnly:
      host: postgresql-musicbrainz-all
      port: 5432

index:
  host: acoustid-index
  port: 6080

redis:
  host: redis
  port: 26379
  sentinel: true
  cluster: acoustid

ratelimits:
  global: 1000

gunicorn:
  timeout: 60
  workers: 2
  threads: 1

labels: {}

# appSecretName: 

# nameOverride:
# fullnameOverride:
