replicaCount: 1

image:
  repository: quay.io/acoustid/acoustid-index
  tag: 2018.01.13
  pullPolicy: IfNotPresent

updater:
  enabled: false

  image:
    repository: quay.io/acoustid/acoustid-index-updater
    tag: v2019.09.30
    pullPolicy: IfNotPresent

  database:
    name: acoustid
    host: postgresql
    port: 5432
    userSecret: acoustid-postgresql-user

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
  # If you do want to specify resources, uncomment the following lines, adjust them as
  # necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# nameOverride:
# fullnameOverride:
