apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  init-cluster-spec.json: {{ .Values.initClusterSpec | toJson | quote }}

  run-wal-g.sh: |
    #!/usr/bin/env bash
    export PGHOST=$STKEEPER_PG_LISTEN_ADDRESS
    export PGUSER=$(cat /etc/secrets/superuser/username)
    export PGPASSWORD=$(cat /etc/secrets/superuser/password)
    exec envdir /etc/wal-g.d/env wal-g "$@"

  run-backup.sh: |
    #!/usr/bin/env bash
    bash /etc/stolon/run-wal-g.sh backup-push $STKEEPER_DATA_DIR/postgres
