apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  init-cluster-spec.json: {{ .Values.initClusterSpec | toJson | quote }}

  run-wal-g.sh: |
    #!/usr/bin/env bash
    export PGUSER=$(cat "$PGUSERFILE")
    export PGPASSWORD=$(cat "$PGPASSWORDFILE")
    exec envdir /etc/wal-g.d/env wal-g "$@"

  run-backup.sh: |
    #!/usr/bin/env bash
    export PGUSER=$(cat "$PGUSERFILE")
    export PGPASSWORD=$(cat "$PGPASSWORDFILE")
    exec envdir /etc/wal-g.d/env wal-g backup-push $STKEEPER_DATA_DIR/postgres
