---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-all
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    {{- include "postgresql.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: stolon-keeper
