{{- if empty .Values.superuser.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.superuserSecretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.superuser.username | b64enc | quote }}
  password: {{ required "Missing superuser password" .Values.superuser.password | b64enc | quote }}
{{- end }}
{{- if empty .Values.replication.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.replicationSecretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.replication.username | b64enc | quote }}
  password: {{ required "Missing replication user password" .Values.replication.password | b64enc | quote }}
{{- end }}
