apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.fullname" . }}-stolon-proxy
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: stolon-proxy
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      {{- include "postgresql.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: stolon-proxy
  template:
    metadata:
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
        app.kubernetes.io/component: stolon-proxy
        component: stolon-proxy
        stolon-cluster: {{ .Release.Name }}
      annotations:
        {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.proxy.annotations }}
        {{- toYaml .Values.proxy.annotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "postgresql.serviceAccountName" . }}
      containers:
        - name: stolon-proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-ec"
            - exec gosu postgres stolon-proxy
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              value: {{ .Release.Name }}
            - name: STPROXY_STORE_BACKEND
              value: kubernetes
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: configmap
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:{{ .Values.metrics.port }}"
            {{- if .Values.debug }}
            - name: STPROXY_DEBUG
              value: "true"
            {{- end }}
          ports:
            - name: postgresql
              containerPort: 5432
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          {{- if .Values.proxy.resources }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
