{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "acoustid-index.fullname" . }}
  labels:
    {{- include "acoustid-index.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "acoustid-index.selectorLabels" . | nindent 4 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
{{- end }}
